server:
  port: 3000
spring:
  application:
    name:redis-provider
  redis:
    host: 192.168.56.150
eureka:
  client:
    service-url:
      defaultZone: http://localhost:1000/eureka/
  instance:
    prefer-ip-address: true